name: domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'
environment:
  sdk: '>=2.18.5 <3.0.0'
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.3.2
  freezed: ^2.2.1
dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  logging: ^1.1.0
  riverpod: ^2.1.1
  freezed_annotation: ^2.2.0
  data:
    path: ../data
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.7
  flutter_bloc: ^8.1.1
flutter:
